# Build settings
gems:
  - jemoji
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh

# Site settings
title: "Short & Easy"
description: > # this means to ignore newlines until "email:"
  Basically gaming after turning 30. Join me on YouTube for my quest for games that are short and easy to play.
#email: a-mail@mail.mail
#blog logo
logo: "/assets/images/channel-icon_trans.png"
# blog cover
cover: "/assets/images/channel-art_clean.jpg"

name: 'Short & Easy'
author: 'Boy'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "https://www.shortandeasy.tv" # the base hostname & protocol for your site
permalink: /news/:title
google_analytics: UA-7720147-32
baseurl: ""
#used to display twitter cards
twitter_handle: '@shortandeasytv'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:       twitter	
    url:	"https://www.twitter.com/shortandeasytv"
  - icon:	youtube
    url:	"/youtube"
  - icon:       twitch	
    url:	"/twitch"

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
